'use client';
import { useGame } from '../../lib/gameStore';
export default function OrderModal(){
 const {state,dispatch}=useGame(); const order=state.orders.find(o=>o.id===state.orderModalId); if(!order)return null;
 return <><div className="overlay" onClick={()=>dispatch({type:'CLOSE_ORDER_MODAL'})}/><div className="sheet"><div className="handle"/><div className="sheet-head"><div><span>주문 상세</span><h2>PO-{order.id}</h2></div><button onClick={()=>dispatch({type:'CLOSE_ORDER_MODAL'})}>×</button></div>
 <div className="status-line"><b>{order.warning?'확인필요':'결제완료'}</b><span>오늘 접수</span></div>
 <section><label>주문 상품</label><div className="product"><div>{order.avatarEmoji}</div><p><b>{order.reqTags.join(' · ')} 포션</b><span>맞춤 제조 상품 · 수량 1</span></p><strong>{order.price.toLocaleString()} G</strong></div></section>
 <section><label>구매자</label><div className="info"><b>{order.name}</b><span>{order.type}</span></div></section>
 <section><label>고객 요청사항</label><div className="request">“{order.request}”</div>{order.backstory&&<p className="subtext">{order.backstory}</p>}</section>
 {order.warning&&<div className="warning">⚠ 주문 내용에 확인이 필요한 항목이 있습니다.</div>}
 <div className="actions"><button className="ghost" onClick={()=>dispatch({type:'DECLINE_ORDER',orderId:order.id})}>주문 취소</button><button className="primary" onClick={()=>dispatch({type:'ACCEPT_ORDER',order})}>제작 시작</button></div>
 <style jsx>{`
 .overlay{position:fixed;inset:0;background:rgba(44,32,40,.28);z-index:80}.sheet{position:fixed;z-index:90;left:50%;bottom:0;transform:translateX(-50%);width:100%;max-width:430px;background:white;border-radius:22px 22px 0 0;padding:10px 18px calc(20px + env(safe-area-inset-bottom));max-height:88vh;overflow:auto}.handle{width:34px;height:4px;border-radius:10px;background:#eadde3;margin:0 auto 12px}.sheet-head{display:flex;justify-content:space-between}.sheet-head span{font-size:10px;color:#a48f99}.sheet-head h2{font-size:20px;margin:2px 0 0}.sheet-head button{border:0;background:#faf3f6;width:32px;height:32px;border-radius:10px;font-size:22px;color:#8f7c85}.status-line{display:flex;justify-content:space-between;align-items:center;background:#fff3f8;border:1px solid #ffdfeb;padding:10px 12px;border-radius:11px;margin:14px 0}.status-line b{font-size:10px;color:#ff4f9a}.status-line span{font-size:9px;color:#a8959e}section{padding:15px 0;border-bottom:1px solid #f5e9ee}label{font-size:10px;color:#9d8b94;display:block;margin-bottom:8px}.product{display:flex;align-items:center;gap:10px}.product>div{width:42px;height:42px;background:#fff0f6;border-radius:11px;display:grid;place-items:center;font-size:22px}.product p{flex:1;margin:0}.product p b{display:block;font-size:12px}.product p span{font-size:9px;color:#a3939b}.product strong{font-size:11px}.info{display:flex;justify-content:space-between}.info b{font-size:12px}.info span{font-size:10px;color:#9b8d94}.request{background:#fbf7f9;border-radius:11px;padding:12px;font-size:12px;line-height:1.6;color:#51474d}.subtext{font-size:10px;color:#9d8d95;line-height:1.5;margin:7px 2px 0}.warning{margin-top:12px;background:#fff4f6;color:#c54f74;border:1px solid #ffd7e2;border-radius:10px;padding:10px;font-size:10px}.actions{display:grid;grid-template-columns:1fr 2fr;gap:8px;margin-top:16px}.actions button{height:46px;border-radius:12px;font-size:12px;font-weight:700}.ghost{background:white;border:1px solid #eadbe2;color:#95858d}.primary{background:#ff4f9a;color:white;border:0}
 `}</style></div></>;
}
