'use client';
import { useEffect } from 'react';
import { useGame,getIngredientById,getMixById,getSpellById } from '../../lib/gameStore';
import { INGREDIENTS,MIX_METHODS,SPELLS } from '../../lib/gameData';
import { computePotion } from '../../lib/gameEngine';
import ResultModal from './ResultModal';

export default function CraftPage(){
 const {state,dispatch}=useGame(); const {selectedIngredientIds,selectedMixId,selectedSpellId,currentResult}=state.craft;
 const selectedIngredients=selectedIngredientIds.map(getIngredientById).filter(Boolean) as any[];
 const selectedMix=getMixById(selectedMixId??''); const selectedSpell=getSpellById(selectedSpellId??'');
 useEffect(()=>{if(selectedIngredients.length){dispatch({type:'SET_RESULT',result:computePotion(selectedIngredients,selectedMix??null,selectedSpell??null)})}},[selectedIngredientIds,selectedMixId,selectedSpellId]);
 const canBrew=Boolean(state.activeOrder&&selectedIngredients.length&&selectedMixId&&selectedSpellId&&currentResult);
 return <div className="craft">
   <header><button onClick={()=>dispatch({type:'SET_TAB',tab:'orders'})}>‹</button><div><span>주문 상품 제작</span><h1>PO-{state.activeOrder?.id ?? '-'}</h1></div><em>제작중</em></header>
   <section className="order"><label>주문 상품</label><div className="order-row"><div className="thumb">{state.activeOrder?.avatarEmoji??'🧪'}</div><div><b>{state.activeOrder?.reqTags.join(' · ') ?? '포션'} 포션</b><p>{state.activeOrder?.name ?? '주문을 선택해주세요'}</p></div><strong>{state.activeOrder?.price.toLocaleString() ?? 0} G</strong></div></section>
   <section><div className="sec-head"><b>1. 재료 선택</b><span>최대 3개</span></div><div className="ingredients">{INGREDIENTS.map(i=>{const sel=selectedIngredientIds.includes(i.id);const stock=state.game.inventory[i.id]??0;return <button key={i.id} disabled={!stock} className={sel?'sel':''} onClick={()=>dispatch({type:'TOGGLE_INGREDIENT',id:i.id})}><span>{i.icon}</span><b>{i.name}</b><small>재고 {stock}</small></button>})}</div></section>
   <section><div className="sec-head"><b>2. 혼합 방식</b></div><div className="options">{MIX_METHODS.map(m=><button key={m.id} className={selectedMixId===m.id?'sel':''} onClick={()=>dispatch({type:'SELECT_MIX',id:m.id})}><span>{m.icon}</span><div><b>{m.name}</b><small>{m.desc}</small></div><i>{selectedMixId===m.id?'✓':''}</i></button>)}</div></section>
   <section><div className="sec-head"><b>3. 마법 처리</b></div><div className="options">{SPELLS.map(s=><button key={s.id} className={selectedSpellId===s.id?'sel':''} onClick={()=>dispatch({type:'SELECT_SPELL',id:s.id})}><span>{s.icon}</span><div><b>{s.name}</b><small>{s.desc}</small></div><i>{selectedSpellId===s.id?'✓':''}</i></button>)}</div></section>
   {currentResult&&<section className="preview"><div className="sec-head"><b>예상 제조 결과</b><span>실시간 계산</span></div><div className="preview-grid"><div><span>효능</span><b>{currentResult.power}</b></div><div><span>안정성</span><b>{currentResult.stability}</b></div><div><span>지속</span><b>{currentResult.duration}</b></div><div><span>왜곡</span><b>{currentResult.chaos}</b></div></div></section>}
   <div className="sticky"><button disabled={!canBrew} onClick={()=>dispatch({type:'SHOW_RESULT_MODAL',show:true})}>{canBrew?'제조 완료 처리':'재료 · 혼합 · 마법 처리를 선택해주세요'}</button></div><ResultModal/>
   <style jsx>{`
    .craft{background:#fffafd;min-height:100vh;color:#2c252a;padding-bottom:90px}header{height:64px;background:white;border-bottom:1px solid #f0dee6;padding:0 16px;display:flex;align-items:center;gap:12px;position:sticky;top:0;z-index:40}header>button{border:0;background:#faf2f6;width:34px;height:34px;border-radius:10px;font-size:24px;color:#7f7077}header div{flex:1}header span{font-size:9px;color:#a18e97}header h1{font-size:16px;margin:1px 0 0}header em{font-style:normal;font-size:9px;background:#fff0f6;color:#ff4f9a;padding:6px 8px;border-radius:20px}section{margin:16px;background:white;border:1px solid #efdee6;border-radius:15px;padding:15px}.order label{font-size:9px;color:#a18f98}.order-row{display:flex;align-items:center;gap:10px;margin-top:8px}.thumb{width:42px;height:42px;background:#fff0f6;border-radius:11px;display:grid;place-items:center;font-size:22px}.order-row>div:nth-child(2){flex:1}.order-row b{font-size:12px}.order-row p{font-size:9px;color:#998992;margin:3px 0}.order-row strong{font-size:11px}.sec-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:11px}.sec-head b{font-size:12px}.sec-head span{font-size:9px;color:#a18e97}.ingredients{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.ingredients button{background:#fff;border:1px solid #eadce3;border-radius:11px;padding:9px 5px;display:flex;flex-direction:column;align-items:center;gap:3px}.ingredients button.sel{background:#fff0f6;border-color:#ff9fc4}.ingredients button:disabled{opacity:.35}.ingredients button span{font-size:23px}.ingredients button b{font-size:9px}.ingredients button small{font-size:8px;color:#a3939b}.options{display:flex;flex-direction:column;gap:7px}.options button{display:flex;align-items:center;gap:10px;background:white;border:1px solid #eadce3;border-radius:11px;padding:10px;text-align:left}.options button.sel{border-color:#ff8fbb;background:#fff3f8}.options button>span{font-size:21px}.options button>div{flex:1}.options b{display:block;font-size:10px}.options small{font-size:8px;color:#9b8b93}.options i{font-style:normal;color:#ff4f9a}.preview{background:#fff6fa}.preview-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.preview-grid div{text-align:center;background:white;border-radius:9px;padding:9px 3px;border:1px solid #f1e0e7}.preview-grid span{display:block;font-size:8px;color:#9d8c95}.preview-grid b{font-size:15px;color:#ff4f9a}.sticky{position:fixed;left:50%;bottom:0;transform:translateX(-50%);width:100%;max-width:430px;background:white;border-top:1px solid #efdee6;padding:10px 16px calc(10px + env(safe-area-inset-bottom));z-index:45}.sticky button{width:100%;height:48px;border:0;border-radius:12px;background:#ff4f9a;color:white;font-size:12px;font-weight:800}.sticky button:disabled{background:#e7dce1;color:#aa9ca3}
   `}</style>
 </div>
}
